/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-21 07:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class validation_005f05_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"UTF-8\">\n");
      out.write("		<title>Insert title here</title>\n");
      out.write("	</head>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		function checkMember() {\n");
      out.write("			var regExpId = /^[a-z|A-Z|ㄱ-ㅎ|ㅏ-ㅣ|가-힣]/\n");
      out.write("			var regExpPasswd = /^[0-9]*$/\n");
      out.write("			var regExpName = /^[가-힣]*$/\n");
      out.write("			var regExpPhone = /^\\d{3}-\\d{3,4}-\\d{4}$/\n");
      out.write("			var regExpEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i\n");
      out.write("			\n");
      out.write("			var form = document.member\n");
      out.write("			\n");
      out.write("			var id = form.id.value\n");
      out.write("			if(!regExpId.test(id)) {\n");
      out.write("				alert(\"아이디는 문자로 시작해 주세요\")\n");
      out.write("				form.id.select()\n");
      out.write("				return\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var passwd = form.passwd.value\n");
      out.write("			if (!regExpPasswd.test(passwd)) {\n");
      out.write("				alert(\"비밀번호는 숫자만 입력해주세요\")\n");
      out.write("				form.passwd.select()\n");
      out.write("				return\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var name = form.name.value\n");
      out.write("			if (!regExpName.test(name)) {\n");
      out.write("				alert(\"이름은 한글만 입력해주세요\")\n");
      out.write("				form.name.select()\n");
      out.write("				return\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var phone = form.phone1.value + \"-\" + form.phone2.value + \"-\" + form.phone3.value\n");
      out.write("			if (!regExpPhone.test(phone)) {\n");
      out.write("				alert(\"연락처 입력을 확인해 주세요\")\n");
      out.write("				form.phone2.select()\n");
      out.write("				return\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var email = form.email.value\n");
      out.write("			if (!regExpEmail.test(email)) {\n");
      out.write("				alert(\"이메일 입력을 확인해 주세요\")\n");
      out.write("				form.email.select()\n");
      out.write("				return\n");
      out.write("			}\n");
      out.write("			form.submit()\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("	<body>\n");
      out.write("		<h3>회원가입</h3>\n");
      out.write("		<form action=\"validation_05p.jsp\" name=\"member\" method=\"post\">\n");
      out.write("			아이디 : <input type=\"text\" name=\"id\"> <br>\n");
      out.write("			비밀번호 : <input type=\"password\" name=\"passwd\"> <br>\n");
      out.write("			이름 : <input type=\"text\" name=\"name\"><br>\n");
      out.write("			연락처 :\n");
      out.write("			<select name=\"phone1\">\n");
      out.write("				<option value=\"010\">010</option>\n");
      out.write("				<option value=\"011\">011</option>\n");
      out.write("				<option value=\"016\">016</option>\n");
      out.write("				<option value=\"017\">017</option>\n");
      out.write("				<option value=\"018\">018</option>\n");
      out.write("				<option value=\"019\">019</option>\n");
      out.write("			</select>\n");
      out.write("			- <input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone2\">\n");
      out.write("			- <input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone3\"><br>\n");
      out.write("			이메일 : <input type=\"text\" name=\"email\"> <br>\n");
      out.write("			<input type=\"button\" value=\"가입하기\" onclick=\"checkMember()\">\n");
      out.write("		</form>\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
